version: '3'

services:
  apollo:
    image: node:16
    working_dir: /usr/app
    environment:
      - PORT=5000
      - NX_URI_MONGO=mongodb://mongo/dt-auth
      - NX_JWT_SECRET=SECRET_AUTH
    depends_on:
      - mongo
    ports:
      - '5000:5000'
      - "9229:9229"
    volumes:
      - ./:/usr/app
      - /node_modules
    command: yarn start presentation-apollo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
