name: Node.js Package

on:
  push:
    branches: [ main ]
    paths:
    - 'libs/authenticator/**'

env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      - run: yarn lint authenticator
      - run: yarn test authenticator
      - run: yarn build authenticator
      - run: yarn publish dist/libs/authenticator
